docs: fix docs for toHaveScreenshot
microsoft/playwright pull request #14280
Opened 2022-05-19 14:18 UTC by aslushnikov

Fixes #14226

2022-05-19 14:54 UTC, rwoll requested changes

2022-05-19 14:54 UTC, rwoll commented on docs/src/api/class-locatorassertions.md
> +This funciton will wait until two consecutive locator screenshots
```suggestion
This function will wait until two consecutive locator screenshots
```

2022-05-19 14:54 UTC, rwoll commented on docs/src/api/class-pageassertions.md
> +This funciton will wait until two consecutive page screenshots
```suggestion
This function will wait until two consecutive page screenshots
```

2022-05-19 14:54 UTC, rwoll commented on docs/src/api/class-pageassertions.md
> +This funciton will wait until two consecutive page screenshots
```suggestion
This function will wait until two consecutive page screenshots
```

2022-05-20 18:24 UTC, pavelfeldman approved these changes

2022-05-24 17:54 UTC, merged