docs(test-advanced-js.md): add instructions for tracing during global setup
microsoft/playwright pull request #14891
Opened 2022-06-15 21:09 UTC by stephenkilbourn

fixes #14889

2022-06-15 22:25 UTC, dgozman reviewed
Great PR! Just a couple of comments and this is good to go.

2022-06-15 22:25 UTC, dgozman commented on docs/src/test-advanced-js.md
> +      }).then(() => {
You can just `await page.close()` instead of chaining with `then`.

2022-06-15 22:25 UTC, dgozman commented on docs/src/test-advanced-js.md
> +  const browser = await chromium.launch();
The snippet should close the browser.

2022-06-15 22:43 UTC, stephenkilbourn commented on docs/src/test-advanced-js.md
> +  const browser = await chromium.launch();
updated

2022-06-16 08:29 UTC, mxschmitt requested changes

2022-06-16 08:29 UTC, mxschmitt commented on docs/src/test-advanced-js.md
> +  const page = await browser.newPage();
```suggestion
  const context = await browser.newPage();
  const page = await context.newPage();
```

2022-06-16 08:29 UTC, mxschmitt commented on docs/src/test-advanced-js.md
> +    .tracing.start({ screenshots: true, snapshots: true });
```suggestion
    await context.tracing.start({ screenshots: true, snapshots: true });
```

2022-06-16 08:29 UTC, mxschmitt commented on docs/src/test-advanced-js.md
> +      })
```suggestion
    await context.tracing.stop({
        path: `./test-results/setup-trace.zip`,
    })
```

2022-06-16 08:29 UTC, mxschmitt commented on docs/src/test-advanced-js.md
> +      });
```suggestion
    await context.tracing.stop({
        path: `./test-results/failed-setup-trace.zip`,
    });
```

2022-06-16 08:29 UTC, mxschmitt commented on docs/src/test-advanced-js.md
> +  const page = await browser.newPage();
```suggestion
  const context = await browser.newContext();
  const page = await context.newPage();
```

2022-06-16 08:29 UTC, mxschmitt commented on docs/src/test-advanced-js.md
> +      .tracing.start({ screenshots: true, snapshots: true });
```suggestion
    await context.tracing.start({ screenshots: true, snapshots: true });
```

2022-06-16 08:29 UTC, mxschmitt commented on docs/src/test-advanced-js.md
> +      })
```suggestion
    await context.tracing.stop({
        path: `./test-results/setup-trace.zip`,
    })
```

2022-06-16 08:29 UTC, mxschmitt commented on docs/src/test-advanced-js.md
> +      throw error;
```suggestion
    await context.tracing.stop({
        path: `./test-results/failed-setup-trace.zip`,
    });
    await page.close();
    throw error;
```

2022-06-16 16:44 UTC, mxschmitt approved these changes

2022-06-16 16:45 UTC, merged

2022-06-16 20:35 UTC, azad-derakhshani-GS commented
Actually there is a typo in what was merged (I was just checking the added doc to implement the traces) in this part:

`and you must ensure that of your that you [stop tracing](./api/class-tracing.md#tracing-stop) if an error occurs before that error is thrown.`

I assume it should be 
`and you must ensure that you [stop tracing](./api/class-tracing.md#tracing-stop) if an error occurs before that error is thrown.`

I'll create an issue and PR for that.