feat(test runner): add --trace cli option
microsoft/playwright pull request #16277
Opened 2022-08-04 23:26 UTC by dgozman

2022-08-04 23:38 UTC, pavelfeldman approved these changes

2022-08-04 23:40 UTC, Mone71 commented
Thanks

2022-08-05 00:18 UTC, rwoll requested changes

2022-08-05 00:18 UTC, rwoll commented on packages/playwright-test/src/cli.ts
> +  command.option('--trace <mode>', `Force tracing mode, can be ${kTraceModes.map(mode => `"${mode}"`).join(', ')}`);
Why is `<mode>` required? If `<mode>`. I'd expect it to default to `on`. Doing `--trace on` seems redundant for a command line switch.

2022-08-05 00:19 UTC, rwoll commented on packages/playwright-test/src/cli.ts
> +  command.option('--trace <mode>', `Force tracing mode, can be ${kTraceModes.map(mode => `"${mode}"`).join(', ')}`);
Comment edited as something got lost when I hit save!

2022-08-05 15:54 UTC, rwoll approved these changes
We can't different between `--trace a.spec.ts` and `--trace <mode>` nicely so ignore my last review!

2022-08-05 16:20 UTC, merged